import json

def code_cell(source: str):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source
    }

def md_cell(source: str):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


cells = []

cells.append(md_cell(
    "# AutoPilot — Wan 2.2 TI2V 5B Headless API\n"
    "Runs the official **Wan 2.2 TI2V 5B** (Text/Image-to-Video) model via a headless ComfyUI "
    "FastAPI server exposed through Ngrok.\n\n"
    "Your local AutoPilot pipeline sends `POST /generate_video` and gets back an MP4."
))

# ── Cell 1: Install deps ──────────────────────────────────────────────────────
cells.append(code_cell(
    "# Cell 1 — Install dependencies\n"
    "!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121\n"
    "!pip install -q xformers\n"
    "!pip install -q diffusers transformers accelerate safetensors huggingface_hub\n"
    "!pip install -q opencv-python pillow numpy requests imageio imageio-ffmpeg\n"
    "!pip install -q fastapi uvicorn pyngrok python-multipart\n"
    "!apt-get -y install -qq aria2 ffmpeg\n"
    'print("✅ Dependencies installed")\n'
))

# ── Cell 2: Clone ComfyUI ─────────────────────────────────────────────────────
cells.append(code_cell(
    "# Cell 2 — Clone ComfyUI\n"
    "import os, sys\n"
    "\n"
    "COMFY_DIR = '/kaggle/working/ComfyUI'\n"
    "if not os.path.exists(COMFY_DIR):\n"
    "    os.system('cd /kaggle/working && git clone https://github.com/comfyanonymous/ComfyUI.git')\n"
    "    print('✅ ComfyUI cloned')\n"
    "else:\n"
    "    print('✅ ComfyUI already present')\n"
    "\n"
    "sys.path.insert(0, COMFY_DIR)\n"
    'print("✅ ComfyUI on sys.path")\n'
))

# ── Cell 3: Download models ───────────────────────────────────────────────────
cells.append(code_cell(
    "# Cell 3 — Download Wan 2.2 model files (runs once; cached on re-run)\n"
    "import os\n"
    "\n"
    "BASE = 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files'\n"
    "WAN21_BASE = 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files'\n"
    "\n"
    "DIRS = {\n"
    "    'diffusion': '/kaggle/working/ComfyUI/models/diffusion_models',\n"
    "    'text_enc' : '/kaggle/working/ComfyUI/models/text_encoders',\n"
    "    'vae'      : '/kaggle/working/ComfyUI/models/vae',\n"
    "    'clip_vis' : '/kaggle/working/ComfyUI/models/clip_vision',\n"
    "}\n"
    "for d in DIRS.values():\n"
    "    os.makedirs(d, exist_ok=True)\n"
    "\n"
    "def dl(url, dest_dir, fname):\n"
    "    dest = os.path.join(dest_dir, fname)\n"
    "    if os.path.exists(dest):\n"
    "        print(f'  ⏭  Already cached: {fname}')\n"
    "        return\n"
    "    print(f'  📥 Downloading {fname} ...')\n"
    "    os.system(f\"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M '{url}' -d '{dest_dir}' -o '{fname}'\")\n"
    "    print(f'  ✅ {fname} done')\n"
    "\n"
    "print('Downloading Wan 2.2 TI2V 5B diffusion model (~9.3 GB)...')\n"
    "dl(f'{BASE}/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors',\n"
    "   DIRS['diffusion'], 'wan2.2_ti2v_5B_fp16.safetensors')\n"
    "\n"
    "print('Downloading UMT5-XXL text encoder FP8 (~6.3 GB)...')\n"
    "dl(f'{BASE}/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors',\n"
    "   DIRS['text_enc'], 'umt5_xxl_fp8_e4m3fn_scaled.safetensors')\n"
    "\n"
    "print('Downloading Wan 2.2 VAE (~1.3 GB)...')\n"
    "dl(f'{BASE}/vae/wan2.2_vae.safetensors',\n"
    "   DIRS['vae'], 'wan2.2_vae.safetensors')\n"
    "\n"
    "print('Downloading CLIP Vision H (~0.6 GB)...')\n"
    "dl(f'{WAN21_BASE}/clip_vision/clip_vision_h.safetensors',\n"
    "   DIRS['clip_vis'], 'clip_vision_h.safetensors')\n"
    "\n"
    'print("\\n✅ All models downloaded")\n'
))

# ── Cell 4: GPU check ─────────────────────────────────────────────────────────
cells.append(code_cell(
    "# Cell 4 — Verify GPU\n"
    "import torch\n"
    "\n"
    "print('GPU Information:')\n"
    "print('=' * 60)\n"
    "print(f'PyTorch: {torch.__version__}')\n"
    "if torch.cuda.is_available():\n"
    "    for i in range(torch.cuda.device_count()):\n"
    "        p = torch.cuda.get_device_properties(i)\n"
    "        print(f'  GPU {i}: {p.name}  {p.total_memory/1024**3:.1f} GB')\n"
    "    print('\\n✅ Ready to serve')\n"
    "else:\n"
    "    raise RuntimeError('No GPU — go to Kaggle Settings > Accelerator and select GPU T4 x2')\n"
))

# ── Cell 5: FastAPI server ────────────────────────────────────────────────────
cells.append(code_cell(
    "# Cell 5 — Headless ComfyUI + FastAPI + Ngrok\n"
    "#\n"
    "# BEFORE RUNNING:\n"
    "#   Replace YOUR_NGROK_TOKEN with a free token from https://dashboard.ngrok.com/get-started/your-authtoken\n"
    "#\n"
    "# AFTER RUNNING:\n"
    "#   Copy the printed URL and add to your local .env:\n"
    "#   KAGGLE_NGROK_URL=https://xxxx.ngrok-free.app\n"
    "\n"
    "NGROK_TOKEN = 'YOUR_NGROK_TOKEN'  # <-- REPLACE THIS\n"
    "\n"
    "# ─────────────────────────────────────────────────────────────────────────\n"
    "import gc, os, random, sys\n"
    "import numpy as np\n"
    "from pathlib import Path\n"
    "import torch\n"
    "import imageio\n"
    "\n"
    "sys.path.insert(0, '/kaggle/working/ComfyUI')\n"
    "from nodes import NODE_CLASS_MAPPINGS\n"
    "\n"
    "OUTPUT_DIR = '/kaggle/working/output'\n"
    "INPUT_DIR  = '/kaggle/working/input'\n"
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n"
    "os.makedirs(INPUT_DIR,  exist_ok=True)\n"
    "\n"
    "def _clear():\n"
    "    gc.collect()\n"
    "    if torch.cuda.is_available():\n"
    "        torch.cuda.empty_cache()\n"
    "        torch.cuda.ipc_collect()\n"
    "\n"
    "\n"
    "def generate_video(\n"
    "    image_path,\n"
    "    positive_prompt,\n"
    "    negative_prompt='text, watermark, ugly, worst quality, low quality, blurry',\n"
    "    width=832,\n"
    "    height=480,\n"
    "    seed=0,\n"
    "    steps=30,\n"
    "    cfg=6.0,\n"
    "    frames=49,\n"
    "    fps=16,\n"
    "):\n"
    "    \"\"\"Run Wan 2.2 TI2V 5B via headless ComfyUI nodes. Returns path to MP4.\"\"\"\n"
    "    if seed == 0:\n"
    "        seed = random.randint(0, 2**32 - 1)\n"
    "\n"
    "    with torch.inference_mode():\n"
    "        # 1. Text encoder\n"
    "        print('[1/6] Loading text encoder...')\n"
    "        clip    = NODE_CLASS_MAPPINGS['CLIPLoader']().load_clip(\n"
    "                      'umt5_xxl_fp8_e4m3fn_scaled.safetensors', 'wan', 'default')[0]\n"
    "        pos_cond = NODE_CLASS_MAPPINGS['CLIPTextEncode']().encode(clip, positive_prompt)[0]\n"
    "        neg_cond = NODE_CLASS_MAPPINGS['CLIPTextEncode']().encode(clip, negative_prompt)[0]\n"
    "        del clip; _clear()\n"
    "\n"
    "        # 2. CLIP Vision + image (I2V) or skip (T2V)\n"
    "        loaded_image = None\n"
    "        clip_vis_out = None\n"
    "        if image_path and Path(image_path).exists():\n"
    "            print('[2/6] Encoding reference image (I2V mode)...')\n"
    "            loaded_image = NODE_CLASS_MAPPINGS['LoadImage']().load_image(image_path)[0]\n"
    "            clip_vis     = NODE_CLASS_MAPPINGS['CLIPVisionLoader']().load_clip('clip_vision_h.safetensors')[0]\n"
    "            clip_vis_out = NODE_CLASS_MAPPINGS['CLIPVisionEncode']().encode(clip_vis, loaded_image, 'none')[0]\n"
    "            del clip_vis; _clear()\n"
    "        else:\n"
    "            print('[2/6] No image — running in T2V mode')\n"
    "\n"
    "        # 3. VAE\n"
    "        print('[3/6] Loading VAE...')\n"
    "        vae = NODE_CLASS_MAPPINGS['VAELoader']().load_vae('wan2.2_vae.safetensors')[0]\n"
    "\n"
    "        # 4. Prepare latents (TI2V conditioning)\n"
    "        print('[4/6] Preparing latents...')\n"
    "        if loaded_image is not None:\n"
    "            # Try WanImageToVideo node (ComfyUI >= 0.3.x ships this for Wan 2.2)\n"
    "            wan_node_cls = NODE_CLASS_MAPPINGS.get('WanImageToVideo')\n"
    "            if wan_node_cls is None:\n"
    "                # Fallback key name\n"
    "                wan_node_cls = NODE_CLASS_MAPPINGS.get('Wan Image To Video')\n"
    "            if wan_node_cls:\n"
    "                pos_cond, neg_cond, latents = wan_node_cls().encode(\n"
    "                    pos_cond, neg_cond, vae,\n"
    "                    width, height, frames, 1,\n"
    "                    loaded_image, clip_vis_out\n"
    "                )\n"
    "            else:\n"
    "                # Older ComfyUI — use empty latent and rely on text prompt only\n"
    "                print('  WanImageToVideo node not found, falling back to T2V')\n"
    "                latents = NODE_CLASS_MAPPINGS['EmptyLatentImage']().generate(width, height, 1)[0]\n"
    "        else:\n"
    "            latents = NODE_CLASS_MAPPINGS['EmptyLatentImage']().generate(width, height, 1)[0]\n"
    "\n"
    "        # 5. UNet + KSampler\n"
    "        print('[5/6] Loading UNet and sampling (this takes a few minutes)...')\n"
    "        model = NODE_CLASS_MAPPINGS['UNETLoader']().load_unet(\n"
    "                    'wan2.2_ti2v_5B_fp16.safetensors', 'default')[0]\n"
    "        sampled = NODE_CLASS_MAPPINGS['KSampler']().sample(\n"
    "            model=model, seed=seed, steps=steps, cfg=cfg,\n"
    "            sampler_name='euler', scheduler='simple',\n"
    "            positive=pos_cond, negative=neg_cond,\n"
    "            latent_image=latents, denoise=1.0\n"
    "        )[0]\n"
    "        del model; _clear()\n"
    "\n"
    "        # 6. VAE decode + save MP4\n"
    "        print('[6/6] Decoding and saving...')\n"
    "        decoded  = NODE_CLASS_MAPPINGS['VAEDecode']().decode(vae, sampled)[0]\n"
    "        del vae, sampled; _clear()\n"
    "\n"
    "        out_path = f'{OUTPUT_DIR}/wan22_{seed}.mp4'\n"
    "        frames_np = [(f.cpu().numpy() * 255).astype(np.uint8) for f in decoded]\n"
    "        with imageio.get_writer(out_path, fps=fps) as writer:\n"
    "            for frame in frames_np:\n"
    "                writer.append_data(frame)\n"
    "\n"
    "        print(f'✅ Video saved: {out_path}')\n"
    "        return out_path\n"
    "\n"
    "\n"
    "# ── FastAPI ──────────────────────────────────────────────────────────────────\n"
    "from fastapi import FastAPI, UploadFile, File, Form, HTTPException\n"
    "from fastapi.responses import FileResponse\n"
    "import uvicorn\n"
    "from pyngrok import ngrok\n"
    "\n"
    "app = FastAPI(title='AutoPilot Wan2.2 API', version='1.0.0')\n"
    "\n"
    "@app.get('/health')\n"
    "def health():\n"
    "    return {'status': 'ok', 'model': 'wan2.2_ti2v_5B_fp16'}\n"
    "\n"
    "\n"
    "@app.post('/generate_video')\n"
    "async def api_generate(\n"
    "    image:  UploadFile = File(None),\n"
    "    prompt: str = Form(...),\n"
    "    seed:   int = Form(0),\n"
    "    steps:  int = Form(30),\n"
    "    width:  int = Form(832),\n"
    "    height: int = Form(480),\n"
    "    frames: int = Form(49),\n"
    "):\n"
    "    try:\n"
    "        img_path = None\n"
    "        if image is not None and image.filename:\n"
    "            img_path = f'{INPUT_DIR}/{image.filename}'\n"
    "            with open(img_path, 'wb') as fh:\n"
    "                fh.write(await image.read())\n"
    "\n"
    "        out_mp4 = generate_video(\n"
    "            image_path=img_path,\n"
    "            positive_prompt=prompt,\n"
    "            seed=seed, steps=steps,\n"
    "            width=width, height=height, frames=frames,\n"
    "        )\n"
    "        return FileResponse(out_mp4, media_type='video/mp4', filename='output.mp4')\n"
    "\n"
    "    except Exception as exc:\n"
    "        import traceback\n"
    "        raise HTTPException(status_code=500, detail=traceback.format_exc())\n"
    "\n"
    "\n"
    "# ── Launch ───────────────────────────────────────────────────────────────────\n"
    "ngrok.set_auth_token(NGROK_TOKEN)\n"
    "tunnel = ngrok.connect(8000)\n"
    "print('\\n' + '=' * 60)\n"
    "print('  AUTOPILOT WAN 2.2 API READY')\n"
    "print(f'  Public URL : {tunnel.public_url}')\n"
    "print(f'  Add to .env: KAGGLE_NGROK_URL={tunnel.public_url}')\n"
    "print(f'  Health check: {tunnel.public_url}/health')\n"
    "print('=' * 60 + '\\n')\n"
    "uvicorn.run(app, host='0.0.0.0', port=8000)\n"
))

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {"name": "python", "version": "3.10.0"},
        "accelerator": "GPU"
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("autopilot_kaggle.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print("autopilot_kaggle.ipynb written successfully")
