import json

with open("autopilot_kaggle.ipynb", "r", encoding="utf-8") as f:
    notebook = json.load(f)

NEW_CELL2_SOURCE = [
    "# =============================================================================\n",
    "# CELL 2 -- PRE-LOAD GPU MODELS IN SUBPROCESS (Zero-VRAM Leakage Guard)\n",
    "# =============================================================================\n",
    "import subprocess, sys, os, torch, time\n",
    "\n",
    "if not torch.cuda.is_available():\n",
    "    print('\\u274c No GPU available \\u2014 pipeline will run in CPU-only mode (Pexels + Edge TTS)')\n",
    "else:\n",
    "    num_gpus = torch.cuda.device_count()\n",
    "    gpu_name = torch.cuda.get_device_name(0)\n",
    "    vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9\n",
    "    print(f'GPUs detected: {num_gpus}x {gpu_name} ({vram_gb:.1f} GB VRAM each)')\n",
    "    print()\n",
    "\n",
    "    # -- [1/2] Chatterbox TTS (cuda:0) --\n",
    "    print('[1/2] Chatterbox TTS -- checking/downloading weights (~1.8 GB first time)...')\n",
    "    t0 = time.time()\n",
    "    env0 = {**os.environ,\n",
    "            'TRANSFORMERS_ATTN_IMPLEMENTATION': 'eager',\n",
    "            'CUDA_VISIBLE_DEVICES': '0'}\n",
    "    chat_code = \"\"\"\n",
    "import os, torch\n",
    "os.environ['TRANSFORMERS_ATTN_IMPLEMENTATION'] = 'eager'\n",
    "from chatterbox.tts import ChatterboxTTS\n",
    "model = ChatterboxTTS.from_pretrained(device='cuda:0')\n",
    "print('      Chatterbox weights pre-loaded successfully!')\n",
    "\"\"\"\n",
    "    r = subprocess.run([sys.executable, '-c', chat_code], capture_output=True, text=True, env=env0)\n",
    "    if r.returncode == 0:\n",
    "        print(r.stdout.strip())\n",
    "        print(f'  \\u2705 OK  Chatterbox ready ({time.time()-t0:.0f}s)')\n",
    "    else:\n",
    "        print(f'  \\u26a0\\ufe0f  Chatterbox failed: ' + r.stderr.strip()[-300:])\n",
    "\n",
    "    # -- [2/2] CogVideoX-2B with bitsandbytes NF4 T5 --\n",
    "    # Root cause of all previous OOMs: T5 float16 = 9.5 GB → fragments VRAM\n",
    "    # Fix: bitsandbytes NF4 T5 = ~2.1 GB (module-level, accelerate-compatible)\n",
    "    video_gpu_id = 1 if num_gpus >= 2 else 0\n",
    "    print(f'\\n[2/2] CogVideoX-2B (T5 NF4 + fp16 Transformer) -- cuda:{video_gpu_id}...')\n",
    "    t0 = time.time()\n",
    "\n",
    "    # PYTORCH_ALLOC_CONF MUST be passed via env dict to guarantee\n",
    "    # it's set before CUDA allocator initializes (not just inside the script)\n",
    "    env1 = {**os.environ,\n",
    "            'PYTORCH_ALLOC_CONF': 'expandable_segments:True',\n",
    "            'TOKENIZERS_PARALLELISM': 'false',\n",
    "            'TRANSFORMERS_VERBOSITY': 'error'}\n",
    "\n",
    "    cog_code = f\"\"\"\n",
    "import os\n",
    "# expandable_segments set via parent env -- CUDA allocator already initialized correctly\n",
    "os.environ['TOKENIZERS_PARALLELISM'] = 'false'\n",
    "import torch, gc\n",
    "from transformers import T5EncoderModel, BitsAndBytesConfig\n",
    "from diffusers import CogVideoXPipeline\n",
    "\n",
    "print('      Loading T5 text encoder in NF4 (~2.1 GB vs 9.5 GB fp16)...')\n",
    "bnb_config = BitsAndBytesConfig(\n",
    "    load_in_4bit=True,\n",
    "    bnb_4bit_quant_type='nf4',\n",
    "    bnb_4bit_compute_dtype=torch.float16,\n",
    "    bnb_4bit_use_double_quant=True,\n",
    ")\n",
    "text_encoder = T5EncoderModel.from_pretrained(\n",
    "    'THUDM/CogVideoX-2b',\n",
    "    subfolder='text_encoder',\n",
    "    quantization_config=bnb_config,\n",
    "    torch_dtype=torch.float16,\n",
    "    low_cpu_mem_usage=True,\n",
    ")\n",
    "print('      T5 NF4 loaded. Loading full pipeline...')\n",
    "pipe = CogVideoXPipeline.from_pretrained(\n",
    "    'THUDM/CogVideoX-2b',\n",
    "    text_encoder=text_encoder,\n",
    "    torch_dtype=torch.float16,\n",
    "    use_safetensors=True,\n",
    ")\n",
    "pipe.enable_model_cpu_offload(gpu_id={video_gpu_id})\n",
    "pipe.enable_attention_slicing(slice_size=1)\n",
    "pipe.enable_vae_slicing()\n",
    "pipe.enable_vae_tiling()\n",
    "print('      Running 5-step smoke test...')\n",
    "with torch.no_grad():\n",
    "    pipe(\n",
    "        prompt='a calm ocean wave, cinematic, photorealistic',\n",
    "        height=480, width=720, num_frames=25, num_inference_steps=5,\n",
    "        guidance_scale=6.0,\n",
    "        generator=torch.Generator(device='cpu').manual_seed(42),\n",
    "    )\n",
    "print('      Smoke test completed successfully!')\n",
    "\"\"\"\n",
    "\n",
    "    r = subprocess.run([sys.executable, '-c', cog_code],\n",
    "                       capture_output=True, text=True, env=env1)\n",
    "    if r.returncode == 0:\n",
    "        print(r.stdout.strip())\n",
    "        print(f'  \\u2705 OK  CogVideoX-2B (NF4 T5) ready ({time.time()-t0:.0f}s)')\n",
    "    else:\n",
    "        print(f'  \\u26a0\\ufe0f  CogVideoX failed:')\n",
    "        # Print both stdout and last 500 chars of stderr for diagnosis\n",
    "        if r.stdout.strip():\n",
    "            print(r.stdout.strip())\n",
    "        print('STDERR:', r.stderr.strip()[-500:])\n",
    "        print('      -> Will fall back to LTX-Video or Pollinations FLUX at runtime')\n",
    "\n",
    "    print('\\nVRAM status inside parent Jupyter kernel: 0 bytes allocated (Subprocess isolated)')\n",
    "    print('\\u2705 Setup complete -- proceed directly to Cell 3!')\n"
]

for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and cell.get('id') == 'cell-2-gpu-models':
        cell['source'] = NEW_CELL2_SOURCE
        print("Cell 2 replaced.")

with open("autopilot_kaggle.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print("Notebook written successfully.")
