import json

with open("autopilot_kaggle.ipynb", "r", encoding="utf-8") as f:
    notebook = json.load(f)

NEW_CELL2_SOURCE = [
    "# =============================================================================\n",
    "# CELL 2 -- PRE-LOAD GPU MODELS IN SUBPROCESS (Zero-VRAM Leakage Guard)\n",
    "# =============================================================================\n",
    "import subprocess, sys, os, torch, time\n",
    "\n",
    "if not torch.cuda.is_available():\n",
    "    print('\\u274c No GPU available \\u2014 pipeline will run in CPU-only mode (Pexels + Edge TTS)')\n",
    "else:\n",
    "    num_gpus = torch.cuda.device_count()\n",
    "    gpu_name = torch.cuda.get_device_name(0)\n",
    "    vram_gb  = torch.cuda.get_device_properties(0).total_memory / 1e9\n",
    "    print(f'GPUs detected: {num_gpus}x {gpu_name} ({vram_gb:.1f} GB VRAM each)')\n",
    "    print()\n",
    "\n",
    "    # -- [1/2] Chatterbox TTS (cuda:0) --\n",
    "    print('[1/2] Chatterbox TTS -- checking/downloading weights (~1.8 GB first time)...')\n",
    "    t0 = time.time()\n",
    "    env0 = {**os.environ,\n",
    "            'TRANSFORMERS_ATTN_IMPLEMENTATION': 'eager',\n",
    "            'CUDA_VISIBLE_DEVICES': '0'}\n",
    "    chat_code = \"\"\"\n",
    "import os, torch\n",
    "os.environ['TRANSFORMERS_ATTN_IMPLEMENTATION'] = 'eager'\n",
    "from chatterbox.tts import ChatterboxTTS\n",
    "model = ChatterboxTTS.from_pretrained(device='cuda:0')\n",
    "print('      Chatterbox weights pre-loaded successfully!')\n",
    "\"\"\"\n",
    "    r = subprocess.run([sys.executable, '-c', chat_code], capture_output=True, text=True, env=env0)\n",
    "    if r.returncode == 0:\n",
    "        print(r.stdout.strip())\n",
    "        print(f'  \\u2705 OK  Chatterbox ready ({time.time()-t0:.0f}s)')\n",
    "    else:\n",
    "        print(f'  \\u26a0\\ufe0f  Chatterbox failed: ' + r.stderr.strip()[-300:])\n",
    "\n",
    "    # -- [2/2] Wan2.1 T2V-1.3B --\n",
    "    video_gpu_id = 1 if num_gpus >= 2 else 0\n",
    "    print(f'\\n[2/2] Wan2.1 T2V-1.3B -- cuda:{video_gpu_id}...')\n",
    "    t0 = time.time()\n",
    "\n",
    "    env1 = {**os.environ,\n",
    "            'PYTORCH_CUDA_ALLOC_CONF': 'expandable_segments:True',\n",
    "            'TOKENIZERS_PARALLELISM': 'false',\n",
    "            'TRANSFORMERS_VERBOSITY': 'error'}\n",
    "\n",
    "    wan_code = \"\"\"\n",
    "import os, torch, gc\n",
    "os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'\n",
    "from diffusers import WanPipeline\n",
    "print('      Loading Wan2.1 T2V-1.3B...')\n",
    "pipe = WanPipeline.from_pretrained(\n",
    "    'Wan-AI/Wan2.1-T2V-1.3B-Diffusers',\n",
    "    torch_dtype=torch.float16,\n",
    ")\n",
    "pipe.to(f'cuda:{video_gpu_id}')\n",
    "pipe.enable_attention_slicing()\n",
    "pipe.vae.enable_slicing()\n",
    "print('      Running 5-step smoke test...')\n",
    "with torch.no_grad():\n",
    "    pipe(\n",
    "        prompt='a calm ocean wave, cinematic',\n",
    "        width=832, height=480, num_frames=9,\n",
    "        num_inference_steps=5, guidance_scale=5.0,\n",
    "    )\n",
    "print('      Smoke test completed successfully!')\n",
    "del pipe; gc.collect(); torch.cuda.empty_cache()\n",
    "\"\"\"\n",
    "\n",
    "    r = subprocess.run([sys.executable, '-c', wan_code],\n",
    "                       capture_output=True, text=True, env=env1)\n",
    "    if r.returncode == 0:\n",
    "        print(r.stdout.strip())\n",
    "        print(f'  \\u2705 OK  Wan2.1 ready ({time.time()-t0:.0f}s)')\n",
    "    else:\n",
    "        print(f'  \\u26a0\\ufe0f  Wan2.1 failed:')\n",
    "        # Print both stdout and last 500 chars of stderr for diagnosis\n",
    "        if r.stdout.strip():\n",
    "            print(r.stdout.strip())\n",
    "        print('STDERR:', r.stderr.strip()[-500:])\n",
    "        print('      -> Will fall back to LTX-Video or Pollinations FLUX at runtime')\n",
    "\n",
    "    print('\\nVRAM status inside parent Jupyter kernel: 0 bytes allocated (Subprocess isolated)')\n",
    "    print('\\u2705 Setup complete -- proceed directly to Cell 3!')\n"
]

for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and cell.get('id') == 'cell-2-gpu-models':
        cell['source'] = NEW_CELL2_SOURCE
        print("Cell 2 replaced.")

with open("autopilot_kaggle.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print("Notebook written successfully.")
